simple_things_entity_audit:
    global_ignore_columns:
        - created_at
        - updated_at
        - updated_by
        - created_by
    audited_entities:
        - AppBundle\Entity\AccessControl\Benutzer