# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
    # Session
    session:
        class: Symfony\Component\HttpFoundation\Session\Session
        arguments: ['@session.storage', '@named_attribute_bag', '@session.flash_bag']
    named_attribute_bag:
        class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
    session.handler.pdo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public: false
        arguments:
            - 'mysql:host=%database_host%;port=3306;dbname=%database_name%'
            - { db_table: session, db_username: '%database_user%', db_password: '%database_password%' }

    # ---------------------------------------------------------------------------------------
    # ---------------------------------------------------------------------------------------
    #
    # Bitte hier nur Eintragungen vornehmen, die sich nicht ueber Annotationen an den
    # jeweiligen Service-Klassen loeschen laesst!
    # http://jmsyst.com/bundles/JMSDiExtraBundle/master/annotations
    #
    # ---------------------------------------------------------------------------------------
    # ---------------------------------------------------------------------------------------
