<?php

namespace Npoa\SecurityBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class EntityPermissionController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Npoa\SecurityBundle\Controller\EntityPermissionController();
        return $instance;
    }
}
