<?php

namespace Proxies\__CG__\Npoa\SecurityBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CtrlActPermission extends \Npoa\SecurityBundle\Entity\CtrlActPermission implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Npoa\\SecurityBundle\\Entity\\CtrlActPermission' . "\0" . 'roleName', '' . "\0" . 'Npoa\\SecurityBundle\\Entity\\CtrlActPermission' . "\0" . 'controller', '' . "\0" . 'Npoa\\SecurityBundle\\Entity\\CtrlActPermission' . "\0" . 'action', '' . "\0" . 'Npoa\\SecurityBundle\\Entity\\CtrlActPermission' . "\0" . 'actionAbsolute'];
        }

        return ['__isInitialized__', '' . "\0" . 'Npoa\\SecurityBundle\\Entity\\CtrlActPermission' . "\0" . 'roleName', '' . "\0" . 'Npoa\\SecurityBundle\\Entity\\CtrlActPermission' . "\0" . 'controller', '' . "\0" . 'Npoa\\SecurityBundle\\Entity\\CtrlActPermission' . "\0" . 'action', '' . "\0" . 'Npoa\\SecurityBundle\\Entity\\CtrlActPermission' . "\0" . 'actionAbsolute'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CtrlActPermission $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', []);

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', [$serialized]);

        return parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function setRoleName($roleName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoleName', [$roleName]);

        return parent::setRoleName($roleName);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoleName()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getRoleName();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoleName', []);

        return parent::getRoleName();
    }

    /**
     * {@inheritDoc}
     */
    public function setController($controller)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setController', [$controller]);

        return parent::setController($controller);
    }

    /**
     * {@inheritDoc}
     */
    public function getController()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getController();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getController', []);

        return parent::getController();
    }

    /**
     * {@inheritDoc}
     */
    public function setAction($action)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAction', [$action]);

        return parent::setAction($action);
    }

    /**
     * {@inheritDoc}
     */
    public function getAction()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getAction();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAction', []);

        return parent::getAction();
    }

    /**
     * {@inheritDoc}
     */
    public function setActionAbsolute($actionAbsolute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActionAbsolute', [$actionAbsolute]);

        return parent::setActionAbsolute($actionAbsolute);
    }

    /**
     * {@inheritDoc}
     */
    public function getActionAbsolute()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActionAbsolute', []);

        return parent::getActionAbsolute();
    }

}
